[2024-06-20 00:17:44 +0100] [44073] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['0.0.0.0:8080']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 120
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /Users/administrator/Code/python/gantt-chart
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 503
  group: 20
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: unix:///var/run/syslog
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x101347ce0>
  on_reload: <function OnReload.on_reload at 0x101347e20>
  when_ready: <function WhenReady.when_ready at 0x101347f60>
  pre_fork: <function Prefork.pre_fork at 0x101368180>
  post_fork: <function Postfork.post_fork at 0x1013682c0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x101368400>
  worker_int: <function WorkerInt.worker_int at 0x101368540>
  worker_abort: <function WorkerAbort.worker_abort at 0x101368680>
  pre_exec: <function PreExec.pre_exec at 0x1013687c0>
  pre_request: <function PreRequest.pre_request at 0x101368900>
  post_request: <function PostRequest.post_request at 0x1013689a0>
  child_exit: <function ChildExit.child_exit at 0x101368ae0>
  worker_exit: <function WorkerExit.worker_exit at 0x101368c20>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x101368d60>
  on_exit: <function OnExit.on_exit at 0x101368ea0>
  ssl_context: <function NewSSLContext.ssl_context at 0x101369080>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  header_map: drop
  tolerate_dangerous_framing: False
[2024-06-20 00:17:44 +0100] [44073] [INFO] Starting gunicorn 22.0.0
[2024-06-20 00:17:44 +0100] [44073] [DEBUG] Arbiter booted
[2024-06-20 00:17:44 +0100] [44073] [INFO] Listening at: http://0.0.0.0:8080 (44073)
[2024-06-20 00:17:44 +0100] [44073] [INFO] Using worker: sync
[2024-06-20 00:17:44 +0100] [44074] [INFO] Booting worker with pid: 44074
[2024-06-20 00:17:44 +0100] [44073] [DEBUG] 1 workers
[2024-06-20 00:17:45 +0100] [44074] [DEBUG] Exception while loading the application
Traceback (most recent call last):
  File "/Users/administrator/Code/python/gantt-chart/.venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/Users/administrator/Code/python/gantt-chart/.venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/administrator/Code/python/gantt-chart/.venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/Users/administrator/Code/python/gantt-chart/.venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/Users/administrator/Code/python/gantt-chart/.venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/administrator/Code/python/gantt-chart/.venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/administrator/Code/python/gantt-chart/.venv/lib/python3.12/site-packages/gunicorn/util.py", line 442, in import_app
    raise AppImportError("Application object must be callable.")
gunicorn.errors.AppImportError: Application object must be callable.
[2024-06-20 00:17:45 +0100] [44074] [INFO] Worker exiting (pid: 44074)
[2024-06-20 00:17:45 +0100] [44073] [ERROR] Worker (pid:44074) exited with code 4
[2024-06-20 00:17:45 +0100] [44073] [ERROR] Shutting down: Master
[2024-06-20 00:17:45 +0100] [44073] [ERROR] Reason: App failed to load.
